import { Category } from '@/types'

export const categories: Category[] = [
  {
    id: 'pavimento',
    icon: '🕳️',
    label: 'Buraco / Estrada',
    sublabel: 'Buracos, passeios, asfalto',
    departamento: 'Divisão de Obras Públicas',
    email: 'obras.publicas@cm-viseu.pt',
    color: '#8B5CF6',
    colorDark: '#7C3AED',
    colorClass: 'bg-gradient-purple',
    shadowClass: 'shadow-purple',
  },
  {
    id: 'iluminacao',
    icon: '💡',
    label: 'Iluminação',
    sublabel: 'Candeeiros, postes, escuridão',
    departamento: 'Divisão de Obras e Manutenção',
    email: 'obras@cm-viseu.pt',
    color: '#FBBF24',
    colorDark: '#F59E0B',
    colorClass: 'bg-gradient-yellow',
    shadowClass: 'shadow-yellow-glow',
  },
  {
    id: 'residuos',
    icon: '🗑️',
    label: 'Lixo / Limpeza',
    sublabel: 'Contentores, entulho, sujidade',
    departamento: 'Divisão de Ambiente',
    email: 'ambiente@cm-viseu.pt',
    color: '#22C55E',
    colorDark: '#16A34A',
    colorClass: 'bg-gradient-green',
    shadowClass: 'shadow-green',
  },
  {
    id: 'espacos-verdes',
    icon: '🌳',
    label: 'Árvores / Jardins',
    sublabel: 'Ramos, relva, parques',
    departamento: 'Divisão de Espaços Verdes',
    email: 'espacos.verdes@cm-viseu.pt',
    color: '#10B981',
    colorDark: '#059669',
    colorClass: 'bg-gradient-emerald',
    shadowClass: 'shadow-emerald',
  },
  {
    id: 'agua',
    icon: '💧',
    label: 'Água / Esgotos',
    sublabel: 'Fugas, mau cheiro, tampas',
    departamento: 'Águas de Viseu',
    email: 'aguas@cm-viseu.pt',
    color: '#3B82F6',
    colorDark: '#2563EB',
    colorClass: 'bg-gradient-blue',
    shadowClass: 'shadow-blue',
  },
  {
    id: 'estacionamento',
    icon: '🚗',
    label: 'Estacionamento',
    sublabel: 'Carros mal estacionados',
    departamento: 'Divisão de Trânsito',
    email: 'transito@cm-viseu.pt',
    color: '#EF4444',
    colorDark: '#DC2626',
    colorClass: 'bg-gradient-red',
    shadowClass: 'shadow-red',
  },
  {
    id: 'sinalizacao',
    icon: '🚸',
    label: 'Sinalização',
    sublabel: 'Sinais, semáforos, passadeiras',
    departamento: 'Divisão de Trânsito',
    email: 'transito@cm-viseu.pt',
    color: '#F97316',
    colorDark: '#EA580C',
    colorClass: 'bg-gradient-orange',
    shadowClass: 'shadow-orange',
  },
  {
    id: 'animais',
    icon: '🐕',
    label: 'Animais',
    sublabel: 'Abandonados, feridos, perigosos',
    departamento: 'Divisão de Veterinária',
    email: 'veterinaria@cm-viseu.pt',
    color: '#EC4899',
    colorDark: '#DB2777',
    colorClass: 'bg-gradient-pink',
    shadowClass: 'shadow-pink',
  },
  {
    id: 'edificios',
    icon: '🏚️',
    label: 'Edifícios',
    sublabel: 'Degradados, perigosos, obras',
    departamento: 'Divisão de Urbanismo',
    email: 'urbanismo@cm-viseu.pt',
    color: '#6366F1',
    colorDark: '#4F46E5',
    colorClass: 'bg-gradient-indigo',
    shadowClass: 'shadow-indigo',
  },
  {
    id: 'ruido',
    icon: '🔊',
    label: 'Ruído',
    sublabel: 'Barulho, obras, vizinhos',
    departamento: 'Polícia Municipal',
    email: 'policia.municipal@cm-viseu.pt',
    color: '#14B8A6',
    colorDark: '#0D9488',
    colorClass: 'bg-gradient-teal',
    shadowClass: 'shadow-teal',
  },
  {
    id: 'acessibilidade',
    icon: '♿',
    label: 'Acessibilidade',
    sublabel: 'Rampas, obstáculos, mobilidade',
    departamento: 'Divisão de Obras Públicas',
    email: 'obras.publicas@cm-viseu.pt',
    color: '#8B5CF6',
    colorDark: '#7C3AED',
    colorClass: 'bg-gradient-violet',
    shadowClass: 'shadow-violet',
  },
  {
    id: 'outro',
    icon: '📝',
    label: 'Outro',
    sublabel: 'Qualquer outro assunto',
    departamento: 'Gabinete de Apoio ao Munícipe',
    email: 'geral@cm-viseu.pt',
    color: '#6B7280',
    colorDark: '#4B5563',
    colorClass: 'bg-gradient-gray',
    shadowClass: 'shadow-card',
  },
]
