import { CategoryV2 } from '@/types'

export const categoriesV2: CategoryV2[] = [
  {
    id: 'pavimento',
    label: 'Pavimento',
    sublabel: 'Buracos, passeios, asfalto',
    departamento: 'Divisão de Obras Públicas',
    email: 'obras.publicas@cm-viseu.pt',
    color: '#7C4DFF',
    iconPath: '/v2/icons/Icon_Pavimento.png',
    placeholder: 'Ex: Há um buraco grande na estrada que pode causar acidentes. Está lá há cerca de 2 semanas e tem piorado com a chuva.',
  },
  {
    id: 'iluminacao',
    label: 'Iluminação',
    sublabel: 'Candeeiros, postes, escuridão',
    departamento: 'Divisão de Obras e Manutenção',
    email: 'obras@cm-viseu.pt',
    color: '#FFC107',
    iconPath: '/v2/icons/Icon_Iluminação.png',
    placeholder: 'Ex: O candeeiro da rua está avariado há uma semana. À noite a zona fica completamente às escuras, o que causa insegurança.',
  },
  {
    id: 'limpeza',
    label: 'Limpeza',
    sublabel: 'Contentores, entulho, sujidade',
    departamento: 'Divisão de Ambiente',
    email: 'ambiente@cm-viseu.pt',
    color: '#E91E63',
    iconPath: '/v2/icons/Icon_Limpeza.png',
    placeholder: 'Ex: Há lixo acumulado junto ao contentor que não é recolhido há vários dias. O cheiro está a incomodar os moradores.',
  },
  {
    id: 'jardins',
    label: 'Jardins',
    sublabel: 'Árvores, relva, parques',
    departamento: 'Divisão de Espaços Verdes',
    email: 'espacos.verdes@cm-viseu.pt',
    color: '#8BC34A',
    iconPath: '/v2/icons/Icon_Jardins.png',
    placeholder: 'Ex: Há uma árvore com ramos partidos que ameaçam cair sobre o passeio. A relva do jardim também precisa de ser cortada.',
  },
  {
    id: 'saneamento',
    label: 'Saneamento',
    sublabel: 'Fugas, mau cheiro, tampas',
    departamento: 'Águas de Viseu',
    email: 'aguas@cm-viseu.pt',
    color: '#2196F3',
    iconPath: '/v2/icons/Icon_Saneamento.png',
    placeholder: 'Ex: Há uma fuga de água no passeio que está a criar uma poça permanente. A tampa de saneamento também está solta.',
  },
  {
    id: 'animais',
    label: 'Animais',
    sublabel: 'Abandonados, feridos, perigosos',
    departamento: 'Divisão de Veterinária',
    email: 'veterinaria@cm-viseu.pt',
    color: '#FF9800',
    iconPath: '/v2/icons/Icon_Animais.png',
    placeholder: 'Ex: Vi um cão abandonado nesta zona há 3 dias. Parece estar ferido e precisa de assistência veterinária.',
  },
  {
    id: 'sinalizacao',
    label: 'Sinalização',
    sublabel: 'Sinais, semáforos, passadeiras',
    departamento: 'Divisão de Trânsito',
    email: 'transito@cm-viseu.pt',
    color: '#E91E63',
    iconPath: '/v2/icons/Icon_Sinalização.png',
    placeholder: 'Ex: O sinal de STOP está vandalizado e não se consegue ler. A passadeira também está muito apagada e precisa de ser repintada.',
  },
  {
    id: 'estacionamento',
    label: 'Estacionamento',
    sublabel: 'Carros mal estacionados',
    departamento: 'Divisão de Trânsito',
    email: 'transito@cm-viseu.pt',
    color: '#2196F3',
    iconPath: '/v2/icons/Icon_Estacionamento.png',
    placeholder: 'Ex: Há carros estacionados em cima do passeio que impedem a passagem de peões e cadeiras de rodas.',
  },
  {
    id: 'edificios',
    label: 'Edifícios',
    sublabel: 'Degradados, perigosos, obras',
    departamento: 'Divisão de Urbanismo',
    email: 'urbanismo@cm-viseu.pt',
    color: '#FF9800',
    iconPath: '/v2/icons/Icon_Edifícios.png',
    placeholder: 'Ex: O edifício abandonado tem a fachada a cair e representa perigo para quem passa. Há também graffitis nas paredes.',
  },
  {
    id: 'acessibilidade',
    label: 'Acessibilidade',
    sublabel: 'Rampas, obstáculos, mobilidade',
    departamento: 'Divisão de Obras Públicas',
    email: 'obras.publicas@cm-viseu.pt',
    color: '#7C4DFF',
    iconPath: '/v2/icons/Icon_Acessibilidade.png',
    placeholder: 'Ex: A rampa de acesso para cadeiras de rodas está danificada. Os rebaixamentos do passeio também estão em mau estado.',
  },
  {
    id: 'ruido',
    label: 'Ruído',
    sublabel: 'Barulho, obras, vizinhos',
    departamento: 'Polícia Municipal',
    email: 'policia.municipal@cm-viseu.pt',
    color: '#9E9E9E',
    iconPath: '/v2/icons/Icon_Ruído.png',
    placeholder: 'Ex: Há obras ruidosas fora do horário permitido (antes das 8h ou depois das 20h). Isto acontece há vários dias.',
  },
  {
    id: 'outro',
    label: 'Outro',
    sublabel: 'Qualquer outro assunto',
    departamento: 'Gabinete de Apoio ao Munícipe',
    email: 'geral@cm-viseu.pt',
    color: '#BDBDBD',
    iconPath: '/v2/icons/Icon_Outros.png',
    placeholder: 'Ex: Descreva o problema que encontrou da forma mais detalhada possível, indicando há quanto tempo existe e o impacto que tem.',
  },
]

export const urgencyOptionsV2 = [
  {
    id: 'pouco_urgente' as const,
    label: 'Pouco Urgente',
    color: '#4CAF50',
    bgColor: '#E8F5E9',
    iconPath: '/v2/icons/Icon_Pouco_Urgente.png',
  },
  {
    id: 'urgente' as const,
    label: 'Urgente',
    color: '#FFC107',
    bgColor: '#FFF8E1',
    iconPath: '/v2/icons/Icon_Urgente.png',
  },
  {
    id: 'perigoso' as const,
    label: 'Perigoso',
    color: '#E91E63',
    bgColor: '#FCE4EC',
    iconPath: '/v2/icons/Icon_Perigoso.png',
  },
]
