export const freguesias: string[] = [
  'Abraveses',
  'Barreiros e Cepões',
  'Boa Aldeia, Farminhão e Torredeita',
  'Bodiosa',
  'Calde',
  'Campo',
  'Cavernães',
  'Coração de Jesus',
  'Coutos de Viseu',
  'Fragosela',
  'Lordosa',
  'Mundão',
  'Orgens',
  'Povolide',
  'Ribafeita',
  'Ranhados',
  'Repeses',
  'Rio de Loba',
  'Santa Maria de Viseu',
  'Santos Evos',
  'São Cipriano e Vil de Soito',
  'São João de Lourosa',
  'São Pedro de France',
  'Silgueiros',
  'Viseu (Centro Histórico)',
].sort()
